[package]
name = "organize"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = "8.0.0"
walkdir = "2.5"
clap = { version = "4.5", features = ["derive"] }
sha2 = "0.10"
shellexpand = "3.1.1"
tempfile = "3.10"

